### ISSUE TITLE
Problems encountered when dragging tables

### ISSUE THREAD

**Issue by xiangshu233** [NiclasDev63/tiptap-extension-global-drag-handle#5]
Hello, I installed the GlobalDragHandle extension according to the documentation and it displayed the drag handle correctly, but when I encountered the table, the following problems occurred when dragging.

https://github.com/NiclasDev63/tiptap-extension-global-drag-handle/assets/49575330/95422d6e-4078-4a95-b944-410d7b3c1449

**Comment by NiclasDev63** [comment]
Unfortunately i was only able to reproduce a part of your problem because by default in my editor the whole table is selected and not only a row. But to ensure that the row (in my case the whole table) is deleted from the old position after the row/table has been inserted at a new position, you should activate the following option:
![image](https://github.com/NiclasDev63/tiptap-extension-global-drag-handle/assets/83044113/383114b2-347d-4528-84a5-6e56aa459274)

**Comment by xiangshu233** [comment]
Thanks, it worked for me, thanks for the plugin, I'm still a noob😺

**Comment by kobe651jp** [comment]
@xiangshu233 

I have exactly the same problem and following the advice above did not work for me.

Can you share your code? Did you do anything else?

My code as follows

```
import Table from "@tiptap/extension-table";
import TableCell from "@tiptap/extension-table-cell";
import TableHeader from "@tiptap/extension-table-header";
import TableRow from "@tiptap/extension-table-row";

  Table.configure({
    resizable: true,
    allowTableNodeSelection: true,
  }),
  TableRow,
  TableHeader,
  TableCell,

```
